### ISSUE TITLE
提示gif生成成功，但是见不到gif文件

### ISSUE THREAD

**Issue by assidence** [mudssky/mpv-config#1]
你好，左上角提示gif生成成功，但是在视频文件目录和mvp根目录都找不到生成的gif文件
![image](https://user-images.githubusercontent.com/15117775/121799214-685ecc00-cc5d-11eb-8185-8c14fb56ce5e.png)

**Comment by mudssky** [comment]
这个我默认是在视频打开的位置生成的

这个需要ffmpeg.exe添加到环境变量里才能执行，因为是调用ffmpeg实现的。
具体就是执行你图里第一行的命令。

**Comment by mudssky** [comment]
核心就是我下面这行命令，只不过要在命令行执行的话文件名要处理一下(比如用引号包裹)，因为有些符号是命令行的特殊符号。
具体可以看我的这篇文章 https://www.jianshu.com/p/b3a837f1dad4

```powershell
ffmpeg -v warning -ss 549.549 -copyts -i input.mkv -to 579.996 -loop 0 -vf fps=8,scale=iw/3:ih/3,subtitles='./input.ass':si=0 -ss 549.549 output[550-580].webp
